<?php

session_start();

require_once 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;
$dompdf = new Dompdf();
$html = '<h1 style="color:blue;">Hello World!</h1><p>A PDF generated by DomPDF library.</p>';
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();


//var_dump($dompdf);
// preview pdf
$dompdf->stream('newfile',array('Attachment'=>0));

if($Download)
{

echo "your file has been downloaded successfully.";	
}	
else {
echo "Error in download.";
	}







?>